export const UPDATE_BROKER_CONFIGURATIONS = "UPDATE_BROKER_CONFIGURATIONS";
export const UPDATE_BROKER_CONNECTIONS = "UPDATE_BROKER_CONNECTIONS";
export const UPDATE_SYSTEM_STATUS = "UPDATE_SYSTEM_STATUS";
export const UPDATE_TOPIC_TREE = "UPDATE_TOPIC_TREE";
export const UPDATE_USERS = "UPDATE_USERS";