export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USERS = 'UPDATE_USERS';
export const UPDATE_USER_ROLES = 'UPDATE_USER_ROLES';
export const UPDATE_USER_GROUPS = 'UPDATE_USER_GROUPS';
export const UPDATE_USER_GROUP = 'UPDATE_USER_GROUP';